# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Copy project files
COPY pyproject.toml README.md ./
COPY src ./src

# Install dependencies and project
RUN pip install --upgrade pip \
    && pip install .

# Default command to run the MCP server over stdio
CMD ["python", "-m", "src.server", "stdio"]
